package main

import (
	"fmt"
	"sort"

	"github.com/kubevirt/cluster-network-addons-operator/pkg/monitoring"
	"github.com/kubevirt/cluster-network-addons-operator/tools/metrics-parser"
)

const (
	opening = `# Cluster Network Addons Operator metrics
> This file is auto generated by metricsdocs, run 'make generate-doc' in order to update it.

This document aims to help users that are not familiar with metrics exposed by the Cluster Network Addons Operator.
All metrics documented here are auto-generated by the utility tool 'tools/metricsdocs' and reflects exactly what is being exposed.
## Cluster Network Addons Operator Metrics List
`

	footer = `## Developing new metrics
After developing new metrics or changing old ones, please run 'make generate-doc' to regenerate this document.`
)

func main() {
	metricsList := getMetrics()
	writeToFile(metricsList)
}

func getMetrics() metricsparser.MetricList {
	metricsList := metricsparser.ReadFromPrometheusCR()
	metricsList = metricsparser.MetricsOptsToMetricList(monitoring.MetricsOptsList, metricsList)

	sort.Slice(metricsList, func(i, j int) bool {
		return metricsList[i].Name < metricsList[j].Name
	})

	return metricsList
}

func writeToFile(metricsList metricsparser.MetricList) {
	fmt.Print(opening)
	metricsList.WriteOut()
	fmt.Print(footer)
}
