run:
  timeout: 3m

linters-settings:
  dupl:
    threshold: 150

  funlen:
    lines: 150
    statements: 50

  gci:
    sections:
    - Prefix(github.com/kubevirt/cluster-network-addons-operator)

  goconst:
    min-len: 2
    min-occurrences: 2

  gocritic:
    enabled-tags: [diagnostic, experimental, opinionated, performance, style]
    disabled-checks:
      - dupImport        # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
    settings:
      hugeParam:
        sizeThreshold: 1024
      rangeValCopy:
        sizeThreshold: 1024

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: github.com/kiagnose/kiagnose

  mnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - return

  govet:
    enable:
      - shadow

  lll:
    line-length: 140

  misspell:
    locale: US

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

  stylecheck:
    dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega
      - github.com/kubevirt/cluster-network-addons-operator/test/kubectl
      - github.com/kubevirt/cluster-network-addons-operator/test/operations

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gofmt
    - goheader
    - goimports
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - unparam
    - unused
#    - whitespace
#    - exhaustive
#    - gocritic
#    - gocyclo
#    - gosec
#    - gosimple
#    - lll
#    - mnd
#    - depguard
#    - staticcheck
#    - stylecheck
#    - unconvert