name: Kubevirt IPAM controller Tests
on: [pull_request]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/local/lib/android/sdk
        sudo apt-get update
        sudo eatmydata apt-get purge --auto-remove -y \
          azure-cli aspnetcore-* dotnet-* ghc-* firefox \
          google-chrome-stable \
          llvm-* microsoft-edge-stable mono-* \
          msbuild mysql-server-core-* php-* php7* \
          powershell temurin-* zulu-*

    - name: Run e2e tests
      env:
        KIND_ALLOW_SYSTEM_WRITES: true
      run: automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh

    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-logs
        path: ./test/e2e/.output/*.log
